### ISSUE TITLE
Always uses localhost

### ISSUE THREAD

**Issue by chrisarrison** [mikedm139/CouchPotato.bundle#29]
Hi

I am running plex on centos. Couchpotato is running on another server. I changed the 'cpIP' in DefaultPrefs.json to point to the IP/short name/FQDN of the server Couchpotato is running on and restarted plex. From the logs I can see that the plugin always tries to connect to localhost:

DEBUG (__init__:304) - API_KEY_URL: http://localhost:5050/getkey/

        {
                "id":           "cpIP",
                "label":        "CouchPotato IP",
                "type":         "text",
                "default":      "http://192.168.21.126"

Any idea why it's not picking up the IP?

**Comment by chrisarrison** [comment]
Hi, apologies, I have sorted this via the plex web interface.

**Comment by mikedm139** [comment]
Glad you sorted it out
